OPERATORS :
ARTHEMATIC OPERATORS (+,-,*,/,%)
RELATIONAL OPERATORS (>,<,>=,<=,=,!=)
LOGICAL OPERATORS (AND, OR)
SPECIAL OPERATORS (IN, NOT IN ,BETWEEN, NOT BETWEEN, IS LIKE, NOT LIKE)
SUBQUERY OPERATORS (ALL, ANY)

25) WQTD DEATLIS OF EMPS IF EMPS ARE WORKING AS WAITER OR CHEF ?
SELECT *
FROM EMPS
WHERE JOB = "WAITER" OR JOB = "CHEF";

WHERE JOB = "WAITER" OR "CHEF" --IT IS NOT WORKING BECAUSE IT IS NOT A VALID SYNTAX

26) WQTD FNAME,DOB AND DOJ IF EMPS BORN IN THE YEAR 1995 ?
SELECT FNAME,DOB,DOJ
FROM EMPS
WHERE DOB>="1994-12-31" AND DOB<="1996-01-01";

27) WQTD DETAILS EMPS IF EMPS AS WORKING AS SECURITY AND SETTING SALARY LESS THAN 80000 ?
SELECT *
FROM EMPS
WHERE JOB="SECURITY" AND SAL<="80000";

28) WQTD DETAILS OF EMPS WHO BORN AFTER THE YEAR 1987 AND WORKING AS WAITER,CHEFE,CLEANER OR DELIVERY AN EMPLOYEE IS MALE ?
SELECT *
FROM EMPS
WHERE (DOB>"1987-12-31") AND (JOB="WAITER" OR JOB="CHEFE" OR JOB="CLEANER" OR JOB="DELIVERY") AND GENDER="M";

29) WQTD ITEM NAME AND PRICE FROM MENU_ITEMS TABLE IF ITEM PRICE IS EITHER 250,350, OR 300 ?
SELECT NAME,PRICE
FROM MENU_ITEMS
WHERE PRICE=250 OR PRICE=350 OR PRICE=300;
	OR
WHERE PRICE IN(250,350,300);
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
IN :
-----
IT IS A MULTI-VALUE OPERATOR WHICH TAKES MULTIPLE VALUES AT THE RHS AND SINGLE VALUE AT THE LHS
IT WORKS ON "OR" CONDTIONS.
WHEN TO USE : WHENEVER WE NEED TO COMPAIR/INCLUUDE MULTIPLE VALUES AT A TIME BASED ON "OR" CONDITON THEN WE USE "IN" OPERATOR
SYNTAXX:
-------		   LHS            RHS
	COLUMN_NAME/EXPRESSION IN(V1,V2,.....,Vn);


30) WQTD DETAILS OF EMPS IF EMPS ARE WORKING AS SECURITY,CHEF OR DELIVERY AND HIRED IN THE YEAR 2018 ?
SELECT *
FROM EMPS
WHERE JOB IN("SECURITY","CHEF","DELIVERY") AND DOJ>="2018-01-01" AND DOJ<="2018-12-31";

31) WQTD ITEM NAME FROM MENU_ITEMS TABLE  IF ITEM NAME IS EITHER MASALA DOSA OR FISH CURRY ?
SELECT NAME
FROM MENU_ITEMS
WHERE NAME IN("MASALA DOSA","FISH CURRY");

32) WQTD DETAILS OF EMPS IF EMPS SATAUS IS NOT BUSY OR OFFLINE ? (WITHOUT USING SPECIAL OPERATOR)
SELECT *
FROM EMPS
WHERE STATUS!="BUSY" AND STATUS!=("OFFLINE");
		OR
WHERE STATUS NOT IN("BUSY","OFFLINE");
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

NOT IN :
--------
IT IS A MULTIPLE-VALUE OPRATOR WHICH TASKS MUTILPE VSLUES AT THE RHS AND SINGLE VALUE AT THE LHS.
IT WORKS ON "AND" CONDITIONS
WHEN TO USE : WHENEVER WE USED TO AVOID MULYIPLE-VALUE AT A TIME BASED ON "AND" CONDITION THEN USE "NOT IN" OPERATOR
SYNTAXX:
-------		   LHS            RHS
	COLUMN_NAME/EXPRESSION NOT IN(V1,V2,.....,Vn);



33) WQTD DETAILS OF EMPS WHO BORN IN THE YEAR 1992 AND NOT WORKING AS MANAGER AND CHEF AND HIRED IN THE YEAR 2018 BUT NOT A FEMALE ?
SELECT *
FROM EMPS
WHERE DOB>="1992-01-01" AND DOB<=("1992-12-31") AND JOB NOT IN("MANAGER","CHEF") AND DOJ>="2018-01-01" AND DOJ<="2018-12-31" AND GENDER NOT IN("F");