OPERATORS :
ARTHEMATIC OPERATORS (+,-,*,/,%)
RELATIONAL OPERATORS (>,<,>=,<=,=,!=)
LOGICAL OPERATORS (AND, OR)
SPECIAL OPERATORS (IN, NOT IN ,BETWEEN, NOT BETWEEN, IS LIKE, NOT LIKE)
SUBQUERY OPERATORS (ALL, ANY)

25) WQTD DEATLIS OF EMPS IF EMPS ARE WORKING AS WAITER OR CHEF ?
SELECT *
FROM EMPS
WHERE JOB = "WAITER" OR JOB = "CHEF";

WHERE JOB = "WAITER" OR "CHEF" --IT IS NOT WORKING BECAUSE IT IS NOT A VALID SYNTAX

26) WQTD FNAME,DOB AND DOJ IF EMPS BORN IN THE YEAR 1995 ?
SELECT FNAME,DOB,DOJ
FROM EMPS
WHERE DOB>="1994-12-31" AND DOB<="1996-01-01";

27) WQTD DETAILS EMPS IF EMPS AS WORKING AS SECURITY AND SETTING SALARY LESS THAN 80000 ?
SELECT *
FROM EMPS
WHERE JOB="SECURITY" AND SAL<="80000";

