FUNCTION:
---------
• FUNCTION IS A SET OF QUERY TO PERFORM A SPECIFIC TASK
• IT IS USED TO REDUCE THE QUERY LENGHT

THERE IS TWO TYPES OF FUNCTIONS 
1.USER DEFINE FUNCTION (PROCEDURE,TRIGGER)
2.IN-BUILT FUNCTION (AGGREGATE,CHARACTER,DATE,NUMBER)

i. AGGREGATE FUNCTION : MAX(),MIN(),AVG(),SUM(),COUNT()
----------------------
MAX(): IT IS USED TO OBTAIN MAXIMUM VALUE FROM THE GIVEN COLUMN.
MIN(): IT IS USED TO OBTAIN MINIMUM VALUE FROM THE GIVEN COLUMN.
SUM(): IT IS USED TO OBTAIN TOTAL VALUE FROM THE GIVEN COLUMN.
AVG(): IT IS USED TO OBTAIN AVERAGE VAALUE FROM THE GIVEN COLUMN.
COUNT(): IT IS USED TO OBTAIN NUMBER OF VALUE PRESENT IN GIVEN COLUMN.

CHARACTERISTICS OF AGGREGATE FUNCTION :-
---------------------------------------
1.IT TASK n NUMBER OF INPUT AND GENERATES SINGLE OUTPUT
2.IT EXECUTE GROUP-BY-GROUP
3.WE CAN'T USE NORMAL COLUMN ALONG WITH AGGREGATE FUNCTIONS IN SELECT CLAUSE
4.WE CAN USE ONLY 1 ARGUMENT INSIDE AGGREGATE FUNCTIONS
5.WE CAN'T USE AGGRREGATE FUNCTIONS
6.WE CAN'T US AGGREGATE FUNCTION INSIDE WHERE CLAUSE
7.IT WILL AVOID NULL VALUES
8.WE CAN USE GROUP BY EXPRESSION ALONG WITH AGGREGATE FUNCTION IN SELECT CLAUSE

65) WQTD TOATAL SALARY TO ALL THE WAITERS ?
SELECT SUM(SAL)
FROM EMPS
WHERE JOB="WAITER";

66) WQTD AVG SALARY, TOTAL SALARY , MIN SALARY ,MAX SALARY OF THE EMPS IF EMPS FNAME STARING WITH K OR A ?
SELECT AVG(SAL), SUM(SAL), MIN(SAL), MAX(SAL)
FROM EMPS
WHERE FNAME LIKE "K%" OR FNAME LIKE "A%";

67) WQTD NUMBER OF EMPS WORKING AS WAITER OR DELIVERY ?
SELECT COUNT(*)
FROM EMPS
WHERE JOB="WAITER" OR JOB="DELIVERY";

68) WQTD NUMBER OF UNIQUE JOB ROLE FROM EMPS TABLE ?
SELECT COUNT(DISTINCT JOB)
FROM EMPS;

69) WQTD DIFFERENCE BETWEEN NUMBER OF JOB ROLE AND NUMBER OF UNIQUE JOB ROLES ?
SELECT COUNT(JOB)-COUNT(DISTINCT JOB)
FROM EMPS;
