In the creation of table first we create parent table after than create child table
primary key present in present table and foreign key present in child table

To Create a table in database :
  Syntax1:

CREATE TABLE TABLE_NAME
(
    COLUMN_NAME1 DATATYPE SIGNED/UNSIGNED NULL/NOT NULL,
    COLUMN_NAME1 DATATYPE SIGNED/UNSIGNED NULL/NOT NULL,
    .
    .
    .
    COLUMN_NAME1024 DATATYPE SIGNED/UNSIGNED NULL/NOT NULL,
    CONSTRAINT CONSTRAINT_NAME PRIMARY KEY(COLUMN_NAME),
    CONSTRAINT CONSTRAINT_NAME UNIQUE(COLUMN_NAME),
    CONSTRAINT CONSTRAINT_NAME CHECK(CONDITION),
    CONSTRAINT CONSTRAINT_NAME FOREIGN KEY(COLUMN_NAME) REFERENCES PARENT_TABLE_NAME(COLUMN_NAME)
);


Q)create a student table with 3 columns(Student id, student name, phone number)

CREATE TABLE STUDENT
(
SID INT UNSIGNED NOT NULL,
SNAME VARCHAR(20) NOT NULL,
PHONE BIGINT UNSIGNED NOT NULL,
CONSTRAINT P_SID PRIMARY KEY(SID),
CONSTRAINT U_PH UNIQUE(PHONE),
CONSTRAINT C_PH CHECK(LENGTH(PHONE)=10)
);



Q) Create a branch table with 4 column(branch id, branch name, address, pin code)

CREATE TABLE BRANCH
(
BID INT UNSIGNED NOT NULL,
BNAME VARCHAR(20) NOT NULL,
ADDRESS VARCHAR(30) NOT NULL,
PINCODE INT UNSIGNED NOT NULL,
CONSTRAINT P_BID PRIMARY KEY(BID),
CONSTRAINT U_PIN UNIQUE(PINCODE),
CONSTRAINT C_PIN CHECK(LENGTH(PINCODE)=6)
);



Q) Create a table Product table With 4 column(pid, pname, price, quality)

CREATE TABLE PRODUCT
(
PID INT NOT NULL,
PNAME VARCHAR(10) NOT NULL,
PRICE DECIMAL(5,2) NOT NULL,
QUALITY INT NULL,
CONSTRAINT P_PID PRIMARY KEY(PID),
CONSTRAINT C_PRICE CHECK(PRICE>0),
CONSTRAINT C_QUALITY CHECK(QUALITY>0)
);
