To Create a table in database :
  Syntax2:

CREATE TABLE TABLE_NAME
(
    COLUMN_NAME1 DATATYPE SIGNED/UNSIGNED NULL/NOT NULL CONSTRAINTS,
    COLUMN_NAME1 DATATYPE SIGNED/UNSIGNED NULL/NOT NULL CONSTRAINTS,
    .
    .
    .
    COLUMN_NAME1024 DATATYPE SIGNED/UNSIGNED NULL/NOT NULL CONSTRAINTS,
     CONSTRAINTS FOREIGN KEY(COLUMN_NAME) REFERENCES PARENT_TABLE_NAME(COLUMN_NAME)
);


Q) CREATE A TABLE FACULTY WITH 3 COLUMN(fid, fname, phone)

CREATE TABLE FACULTY
(
FID INT UNSIGNED NOT NULL PRIMARY KEY,
FNAME VARCHAR(20) NOT NULL,
PHONE BIGINT UNSIGNED NOT NULL UNIQUE CHECK(LENGTH(PHONE)=10)
);


Q) Create a table customer with 4 columns with foreign key also

CREATE TABLE CUSTOMER
(
CID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
CNAME VARCHAR(30) NOT NULL,
ADDRESS VARCHAR(100) NOT NULL,
PHONE BIGINT UNSIGNED NOT NULL UNIQUE CHECK(LENGTH(PHONE)=10),
EMAIL VARCHAR(40) NULL,
BALANCE DECIMAL(5,3) UNSIGNED NOT NULL DEFAULT"10",
GENDER ENUM("MALE","FEMALE") NOT NULL,
SID INT UNSIGNED NOT NULL,
CONSTRAINT FOREIGN KEY(SID) REFERENCES STUDENT(SID)
);

