In the creation of table first we create parent table after than create child table
primary key present in present table and foreign key present in child table

tasks :
CREATE A NEW DATABASE TOUR_DATA AND CREATE TABLES(CUSTOMER,DESTINATION,PACKAGES,BOOKING)

// CUSTOMER :
CREATE TABLE CUSTOMER
(
CUSTOMER_ID INT NOT NULL PRIMARY KEY,
FRIST_NAME VARCHAR(50) NULL,
LAST_NAME VARCHAR(50) NULL,
EMAIL VARCHAR(100) NULL,
PHONE_NUMBER VARCHAR(15)
);


// DESTINATION :
CREATE TABLE DESTINATION
(
DESTINATION_ID INT NOT NULL PRIMARY KEY,
DESTINATION_NAMAE VARCHAR(100) NULL,
STATE VARCHAR(50) NULL,
AVERAGE_COST DECIMAL(10,2) NULL
);


// PACKAGES :
CREATE TABLE PACKAGES
(
PACKAGE_ID INT NOT NULL PRIMARY KEY,
DESTINATION_ID INT NOT NULL,
PACKAGES_NAME VARCHAR(100) NULL,
DURATION_DAYS INT NULL,
PRICE DECIMAL(10,2) NULL,
CONSTRAINT FOREIGN KEY(DESTINATION_ID) REFERENCES DESTINATION(DESTINATION_ID)
);


// BOOKINGS :
CREATE TABLE BOOKINGS
(
BOOKING_ID INT NOT NULL PRIMARY KEY,
CUSTOMER_ID INT NOT NULL,
PACKAGE_ID INT NOT NULL,
BOOKING_DATE DATE NULL,
STATUS ENUM("CONFIRMED","CANCELLED","PANDING"),
CONSTRAINT FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
CONSTRAINT FOREIGN KEY(PACKAGE_ID) REFERENCES PACKAGES(PACKAGE_ID)
);


TASK : CREATE A NEW DATABASE HOSPITAL AND CREATE TABLES(PATIENTS,APPOINTMENTS,MEDICATIONS,BILLS,DOCTORS)



//PATIENTS :
CREATE TABLE PATIENTS
(
PAT_ID INT NOT NULL PRIMARY KEY,
PAT_NAME VARCHAR(50) NULL,
DOB DATE NULL,
GENDER CHAR(1) NULL
);


//APPOINTMENTS :
CREATE TABLE APPOINTMENTS
(
APP_ID INT NOT NULL PRIMARY KEY,
DOC_ID INT NOT NULL,
PAT_ID INT NOT NULL,
APP_DATE DATETIME NULL,
STATUS ENUM("SCHEDULED","COMPLETED","CANCELLED"),
CONSTRAINT FOREIGN KEY(DOC_ID) REFERENCES DOCTORS(DOC_ID),
CONSTRAINT FOREIGN KEY(PAT_ID) REFERENCES PATIENTS(PAT_ID)
);

// MEDICATIONS :
CREATE TABLE MEDICATIONS
(
MED_ID INT NOT NULL PRIMARY KEY,
PAT_ID INT NOT NULL,
DOC_ID INT NOT NULL,
MEDICINE_NAME VARCHAR(100) NULL,
DOSSAGE VARCHAR(50) NULL,
START_DATE DATE NULL,
END_DATE DATE NULL,
CONSTRAINT FOREIGN KEY(PAT_ID) REFERENCES PATIENTS(PAT_ID),
CONSTRAINT FOREIGN KEY(DOC_ID) REFERENCES DOCTORS(DOC_ID)
);


// BILLS :
CREATE TABLE BILLS
(
BILL_ID INT NOT NULL PRIMARY KEY,
APP_ID INT NOT NULL,
AMOUNT DECIMAL(10,2) NULL,
PAYMENT_STATUS ENUM("PAID","UNPAID"),
CONSTRAINT FOREIGN KEY(APP_ID) REFERENCES APPOINTMENTS(APP_ID)
);


//DOCTORS :
CREATE TABLE DOCTORS
(
DOC_ID INT NOT NULL PRIMARY KEY,
DOC_NAME VARCHAR(50) NULL,
SPECIALIZATION VARCHAR(50)
);
