Alter : it is used modify the table structure. It is used to add, delete or modify columns in an existing table.

1. To add new column_name :

syntax :
ALTER TABLE table_name
ADD new_column_name new_column_datatype null/not null;

Q) TO ADD COLUMN EMAIL TO STUDENT TABLE
ALTER TABLE STUDENT
ADD EMAIL VARCHAR(20) NOT NULL;


2. To add new column_name after particular column :
syntax :

ALTER TABLE table_name
ADD new_column_name new column_datatype null/not null AFTER existing_column_name;

Q) TO ADD COLUMN BALANCE TO STUDENT TABLE TO PARTICULAR PLACE COLUMN
ALTER TABLE STUDENT
ADD BALANCE INT NULL AFTER SNAME;

3. To add new column in the first position :
syntax :
ALTER TABLE table_name
ADD new_column_name new_column_datatype null/not null FIRST;

Q) TO ADD COLUMN BALANCE TO STUDENT TABLE IN FIRST POSITION
ALTER TABLE STUDENT
ADD BALANCE INT NULL FIRST;

4. To drop column_name :
syntax :
ALTER TABLE table_name
DROP existing_column_name;

Q) TO DROP COLUMN EMAIL FROM STUDENT TABLE
ALTER TABLE STUDENT
DROP EMAIL;

5. To change datatype :
syntax :
ALTER TABLE table_name
MODIFY existing_column_name new_column_datatype null/not null;

Q) TO CHANGE DATATYPE OF COLUMN ADDRESS IN STUDENT TABLE
ALTER TABLE STUDENT
MODIFY ADDRESS CHAR(50) NOT NULL;

6. To change null/not null :
syntax :
ALTER TABLE table_name
MODIFY existing_column_name existing_column_datatype null/not null;

Q) TO CHANGE NULLABILITY OF COLUMN ADDRESS IN COSTOMER TABLE
ALTER TABLE COSTOMER
MODIFY ADDRESS VARCHAR(50) NOT NULL;

7. To change the table name :
syntax :
ALTER TABLE old_table_name
RENAME new_table_name;

Q) TO CHANGE TABLE NAME FACULTY TO DEPARTMENT
ALTER TABLE FACULTY
RENAME DEPARTMENT;

8. To change the column name :
syntax :
ALTER TABLE table_name
CHANGE old_column_name new_column_name existing_column_datatype null/not null;

Q) TO CHANGE COLUMN NAME IN STUDENT TABLE SNAME TO STUDENT_NAME
ALTER TABLE STUDENT
RENAME COLUMN SNAME TO STUDENT_NAME;

Q) TO CHANGE COLUMN NAME IN STUDENT TABLE PHONE TO CONTACT
ALTER TABLE STUDENT
RENAME COLUMN PHONE TO CONTACT;

Q) TO ADD PRIMARY KEY

ALTER TABLE CONSTOMER
ADD PRIMARY KEY();

Q) TO ADD UNIQUE CONSTRAINT

ALTER TABLE CUSTOMER
ADD UNIQUE(EMAIL);

Q) TO ADD CHECK CONSTRAINT


Q) ADD NEW COLUMN

ALTER TABLE DEPARTMENT
ADD SID INT UNSIGNED NOT NULL;

Q) ADD FOREIGN KEY CONSTRAINT

ALTER TABLE DEPARTMENT
ADD FOREIGN KEY(SID) REFERENCES STUDENT(SID);

Q) TO ADD AUTO_INCREMENT

ALTER TABLE PRODUCT
MODIFY PID INT NOT NULL AUTO_INCREMENT;

Q)TO ADD DEFAULT

ALTER TABLE PRODUCT
MODIFY QUALITY INT NULL DEFAULT"100";

Q) TO DROP PRIMARY KEY

ALTER TABLE BRANCH
DROP PRIMARY KEY;

ALTER TABLE PRODUCT
DROP PRIMARY KEY;  (ERROR :ATUO_INCREMENT )

ALTER TABLE STUDENT
DROP PRIMARY KEY; (ERROR : FOREIGN KEY)

Q) TO DROP AUTO_INCREMENT

ALTER TABLE CUSTOMER
MODIFY CID INT UNSIGNED NOT NULL;

Q) TO DROP DEFAULT

ALTER TABLE CUSTOMER
ALTER COLUMN BALANCE
DROP DEFAULT;

Q) TO DROP UNIQUE, CHECK,FOREIGN KEY

ALTER TABLE CUSTOMER
DROP CONSTRAINT PHONE;

TRUNCATE : IT IS USED TO DELETE ALL THE RECORD FROM A TABLE WITHOUT AFFECTING TABLE STRUCTURE

SYNTAX :
TRUNCATE TABLE TABLE_NAME;

Q) TO TRUNCATE THE PRODUCT TBALE

TRUNCATE TABLE PRODUCT;


DROP : IT IS USED TO DELETE OR DROP THE DATABASE, ITS OBJECTS SUCH AS TABLE, VIEW,PROCEDURE,TRIGGER,USER FROM MYSQL.

1. TO DROP TABLE FROM DATABASE:
SYNTAX :
	DROP TABLE TABLE_NAME;

Q) DROP PRODUCT TABLE FROM DATABASE
DROP TABLE PRODUCT;

2. TO DROP DATABASE FROM MYSQL:
SYNTAX :
	DROP DATABASE DATABASE_NAME;

Q) TO DROP CHOMBU DATABASE FROM MYSQL
DROP DATABASE CHOMBU;
