INSERT : INSERT IS USED ADD OR INSERT NEW RECORDS IN THE TABLE.

SYNTAX 1 :
    INSERT INTO TABLE_NAME VALUES(V1,V2,....,Vn);

Q) INSERT VALUES INTO PRODUCT TABLES 
INSERT INTO PRODUCT VALUES(1,"SUNSCREEN",500,1);

Q) INSERT VALUES INTO PRODUCT TABLES MORE THAN ONE ROW
INSERT INTO PRODUCT VALUES(2,"OLD MONK",180,3),(3,"LIPSTICK",300,5);

Q) INSERT VALUES INTO PRODUCT TABLES 
INSERT INTO PRODUCT VALUES(4,"CRICKETBAT",999,2);
