DML (DATA MANIPULATION LANGUAGE) : DML IS USED TO MANIPULATE THE DATA IN THE TABLE. IT INCLUDES THE FOLLOWING COMMANDS.
1.INSERT
2.UPDATE
3.DELETE

INSERT : INSERT IS USED ADD OR INSERT NEW RECORDS IN THE TABLE.

SYNTAX 1 :
    INSERT INTO TABLE_NAME VALUES(V1,V2,....,Vn);

Q) INSERT VALUES INTO PRODUCT TABLES 
INSERT INTO PRODUCT VALUES(1,"SUNSCREEN",500,1);

Q) INSERT VALUES INTO PRODUCT TABLES MORE THAN ONE ROW
INSERT INTO PRODUCT VALUES(2,"OLD MONK",180,3),(3,"LIPSTICK",300,5);

Q) INSERT VALUES INTO PRODUCT TABLES 
INSERT INTO PRODUCT VALUES(4,"CRICKETBAT",999,2);

SYNTAX 2 :

	INSERT INTO TABLE_NAME(COL1,COL2,....COLn) VALUES(V1,V2,...Vn);

Q) INSERT THE VALUES TO THE PRODUCT TABLE

INSERT INTO PRODUCT(PNAME,PRICE,QUALITY,PID) VALUES("KITKAT",20,10,5);

Q) INSERT THE VALUES TO THE PRODUCT TABLE TO MORE THAN ONE ROW

INSERT INTO PRODUCT(PRICE,PNAME,PID,QUALITY) VALUES(999,"WATCH",6,3),(700,"BELT",7,5);

Q) INSERT THE VALUES TO THE PRODUCT TABLE

INSERT INTO PRODUCT(PNAME,PRICE) VALUES("RING",555);


SYNTAX 3 :
	INSERT INTO TABLE_NAME(SELECT_QUERY);

Q) INSERT THE VALUES TO THE PRODUCT TABLE FROM ANOTHER TABLE
INSERT INTO PRODUCT(PID,PNAME,PRICE,QUALITY) SELECT EMPID,ENAME,SALARY,DEPTNO FROM EMPLOYEE;