DQL(DATA QUERY LANGUAGE):SELECT,PROJECTION,SELECTION,JOIN

using the SELECT statement in SQL:

1) WQTD EMPLOYEE FIRST NAME AND LAST NAME FROM EMPS TABLE ?
SELECT FNAME,LNAME
FROM EMPS;

2) WQTD EMPLOYEE FRIST NAME,JOB,SALARY AND DATE OF BIRTH FROM EMPS TABLE ?
SELECT FNAME,JOB,SAL,DOB
FROM EMPS;

3) WQTQ DETAILS OF EMPLOYEES FROM EMPS TABLE
SELECT * FROM EMPS;

4) WQTQ FIRST NAME,STATUS,ANNUAL SALARY OF THE EMPLOYEE FROM EMPS TABLE?
SELECT FNAME,STATUS,SAL*12
FROM EMPS;

using the Expression in SQL:
(
expression is cobination of operands and operators that evaluates to a single value. It can be used in SELECT, WHERE, GROUP BY, HAVING, and ORDER BY clauses. Examples of expressions include arithmetic expressions, string expressions, date expressions, and logical expressions.
10 + 20 = 30 (10,20,30 is operand and +,= is operator)

1.direct values : the values which we are using directly in a expression are called direct values. Example: 10,20,30
2.column names : the column names or variables we are using indirectly in a expression are called column names. Example: SAL,COMM
)

5) WQTQ DETAILS OF EMPLOYEE ALONG WITH ANNUAL COMMISSION FROM EMPS
SELECT *, COMM*12
FROM EMPS;

6)WQTTD FNAME,JOB AND SALARY WITH 25,000/- BONUS ?
SELECT FNAME,JOB,SAL+25000
FROM EMPS;

7) WQTD FNAME,STATUS AND LID AND SALARY WITH 10% HIKE ?
HIKE SYNTAX OR FORMULA :  COLUMN_NAME +(COLUMN_NAME * %HIKE / 100)

SELECT FNAME,STATUS,LID,SAL+(SAL * 10 / 100)
FROM EMPS;

		OR

SELECT FNAME,STATUS,LID,SAL*0.1+SAL
FROM EMPS;

8) WQTD FNAME,JOB,CUSTOMER ID AND SALARY WITH 20% HIKE ?
SELECT FNAME,JOB,CID,SAL+(SAL * 20 / 100)
FROM EMPS;

9) WQTD FNAME,SALARY WITH 30% DEDUCTOIN ?
DEDUCTION SYNTAX OR FORMULA : COLUMN_NAME - (COLUMN_NAME * %DEDUCTION / 100)

SELECT FNAME,SAL-(SAL * 30 / 100)
FROM EMPS;

10) WQTD FNAME,COMMISION WITH 15% HIKE ANNUAL 50% DEDUCTION ?
SELECT FNAME,COMM +(COMM * 15 /100),(SAL*12) - ((SAL*12) * 50 / 100)
FROM EMPS;

11) WQTD FNAME,JOB AND ANNUAL SALARY WITH 10% HIKE AND ANNUAL COOMISSION WITH 20% DEDUCTION ?
SELECT FNAME,JOB,(SAL*12) + ((SAL*12) * 10/100), (COMM *12) - ((COMM *12) * 20/100)
FROM EMPS;


-----------------------------------------------------------------------------------------------------------------------------

WHERE CLAUSE : IT IS USED TO FILTER THE VALUE BASED ON CONDITION IN THE TABLE RECORDS.

14) WQTD FNAME AS FIRST NAME AND JOB IF EMPS FNAME IS KIRAN ?
SELECT FNAME AS "FIRST NAME",JOB
FROM EMPS
WHERE FNAME="KIRAN";

15) WQTD FNAME,SAL AS SALARY,COMM AS COMMISSIONIF EMPS ARE GETTING SALARY MORE THAN 45000 ?
SELECT FNAME,SAL AS SALARY,COMM AS COMMISSION
FROM EMPS
WHERE SAL>45000;

16) WQTD DETAILS OF EMPS IF EMPS ASR WORKING AS WAITER ?
SELECT *
FROM EMPS
WHERE JOB="WAITER";

17) WQTD FNAME,DOB(DATE OF BIRTH) AND DOJ(DATE OF JOINING) IF EMPS BORN AFTER THE YEAR 1993 ?
SELECT FNAME,DOB,DOJ
FROM EMPS
WHERE DOB>"1993-12-31"; --DOB>"YYYY-MM--DD"

18) WQTD FNAME,DOB,DOJ IF EMPS JOINED AFTER THE YEAR 2019 ?
SELECT FNAME,DOB,JOB,DOJ
FROM EMPS
WHERE DOJ>"2019-12-31";

19) WQTD DETAILS OF EMPS WHO HIRED AFTER THE MONTH MARCH OF 2020 ?
SELECT *
FROM EMPS
WHERE DOJ>"2020-03-31";
	OR
WHERE DOJ>="2020-04-01";

20) WQTD FNAME,DOB IF EMPS BORN BEFORE THE YEAR 1994 ?
SELECT FNAME,DOB
FROM EMPS
WHERE DOB<"1993-12-31";
	OR
WHERE DOB<"1994-01-01";

21) WQTD FNAME,ANNUAL SALARY,MANAGER ID IF ANNUAL SALARY IS MORE THAN 5LAKHS ?
SELECT FNAME,SAL*12 AS "ANNUAL SALARY",MGR AS "MANAGER ID"
FROM EMPS
WHERE SAL*12>500000;

22) WQTD FNAME,JOB AND DOJ AND LOCATION ID IF EMPS BORN BEFORE THE MONTH OCTOBER OF 1995 ?
SELECT FNAME,DOB,DOJ,LID
FROM EMPS
WHERE DOB<"1995-10-01";
	OR
WHERE DOB<"1995-09-30";

-------------------------------------------------------------------------------------------------------------------------------------------
DISTINCT :IT IS USED TO AVOID VALUES FROM RESULTANT TABLE.

RULES IN DISTINCT :
-------------------
EITHER * OR DISTINCT KEYWORD MUST BE THE FIRST ARGUMENT IN SELECT CLAUSE.
WE CAN USE MULTIPLE CLOUMNS ALONG WITH DISTINCT KEYWORD BUT IT WILL AVOID COMBINATION OF DUPLICATION VALUES.


23) WQTD UNIQUE JOB ROLES FROM EMPS TAMPS ?
SELECT DISTINCT JOB
FROM EMPS;

24) WQTD UNIQUE COMBINATON OF MGR AND STATUS ?
SELECT DISTINCT MGR,STATUS
FROM EMPS;

