DQL(DATA QUERY LANGUAGE):SELECT,PROJECTION,SELECTION,JOIN

using the SELECT statement in SQL:

1) WQTD EMPLOYEE FIRST NAME AND LAST NAME FROM EMPS TABLE ?
SELECT FNAME,LNAME
FROM EMPS;

2) WQTD EMPLOYEE FRIST NAME,JOB,SALARY AND DATE OF BIRTH FROM EMPS TABLE ?
SELECT FNAME,JOB,SAL,DOB
FROM EMPS;

3) WQTQ DETAILS OF EMPLOYEES FROM EMPS TABLE
SELECT * FROM EMPS;

4) WQTQ FIRST NAME,STATUS,ANNUAL SALARY OF THE EMPLOYEE FROM EMPS TABLE?
SELECT FNAME,STATUS,SAL*12
FROM EMPS;

using the Expression in SQL:
(
expression is cobination of operands and operators that evaluates to a single value. It can be used in SELECT, WHERE, GROUP BY, HAVING, and ORDER BY clauses. Examples of expressions include arithmetic expressions, string expressions, date expressions, and logical expressions.
10 + 20 = 30 (10,20,30 is operand and +,= is operator)

1.direct values : the values which we are using directly in a expression are called direct values. Example: 10,20,30
2.column names : the column names or variables we are using indirectly in a expression are called column names. Example: SAL,COMM
)

5) WQTQ DETAILS OF EMPLOYEE ALONG WITH ANNUAL COMMISSION FROM EMPS
SELECT *, COMM*12
FROM EMPS;

6)WQTTD FNAME,JOB AND SALARY WITH 25,000/- BONUS ?
SELECT FNAME,JOB,SAL+25000
FROM EMPS;

7) WQTD FNAME,STATUS AND LID AND SALARY WITH 10% HIKE ?
HIKE SYNTAX OR FORMULA :  COLUMN_NAME +(COLUMN_NAME * %HIKE / 100)

SELECT FNAME,STATUS,LID,SAL+(SAL * 10 / 100)
FROM EMPS;

		OR

SELECT FNAME,STATUS,LID,SAL*0.1+SAL
FROM EMPS;

8) WQTD FNAME,JOB,CUSTOMER ID AND SALARY WITH 20% HIKE ?
SELECT FNAME,JOB,CID,SAL+(SAL * 20 / 100)
FROM EMPS;

9) WQTD FNAME,SALARY WITH 30% DEDUCTOIN ?
DEDUCTION SYNTAX OR FORMULA : COLUMN_NAME - (COLUMN_NAME * %DEDUCTION / 100)

SELECT FNAME,SAL-(SAL * 30 / 100)
FROM EMPS;

10) WQTD FNAME,COMMISION WITH 15% HIKE ANNUAL 50% DEDUCTION ?
SELECT FNAME,COMM +(COMM * 15 /100),(SAL*12) - ((SAL*12) * 50 / 100)
FROM EMPS;

11) WQTD FNAME,JOB AND ANNUAL SALARY WITH 10% HIKE AND ANNUAL COOMISSION WITH 20% DEDUCTION ?
SELECT FNAME,JOB,(SAL*12) + ((SAL*12) * 10/100), (COMM *12) - ((COMM *12) * 20/100)
FROM EMPS;

