DQL(DATA QUERY LANGUAGE):SELECT,PROJECTION,SELECTION,JOIN

1) WQTD EMPLOYEE FIRST NAME AND LAST NAME FROM EMPS TABLE ?
SELECT FNAME,LNAME
FROM EMPS;

2) WQTD EMPLOYEE FRIST NAME,JOB,SALARY AND DATE OF BIRTH FROM EMPS TABLE ?
SELECT FNAME,JOB,SAL,DOB
FROM EMPS;

3) WQTQ DETAILS OF EMPLOYEES FROM EMPS TABLE
SELECT * FROM EMPS;

4) WQTQ FIRST NAME,STATUS,ANNUAL SALARY OF THE EMPLOYEE FROM EMPS TABLE?
SELECT FNAME,STATUS,SAL*12
FROM EMPS;
