ALIASING : (USING AS KEYWORD) BUT AS IS OPTIONAL
IT IS A PROCESS TO PROVIDE ALTERNATIVE NAME FOR A COLUMN IN RESULTANT TABLE.

RULES:
1. WITH OR WITHOUT USING "AS" KEYWORD WE CAN WRITE ALIAS NAME.
EX : SELECT SAL AS SALARY
     FROM EMPS;

     SELECT SAL SALARY
     FROM EMPS;

2. WE CAN USE MULTIPLE WORDS AS A ALIAS NAME BY USING COTS("") OR BY CONNECTING WORDS UNDERSCORE(_).
EX: SELECT SAL*12 ANNUL_SALARY
    FROM EMPS;
 
    SELECT SAL*12 "ANNUL SALARY"
    FROM EMPS;

12) WQTD ALIAS NAME FOR  ANNUAL SALARY WITH 10% HIKE AND ANNUAL COOMISSION WITH 20% DEDUCTION ?
SELECT FNAME,JOB,(SAL*12) + ((SAL*12) * 10/100) AS "ANNUAL SALARY WITH 10% HIKE", (COMM *12) - ((COMM *12) * 20/100) AS   " COOMISSION WITH 20% DEDUCTION"
FROM EMPS;

13) WQTD FNAME AS FIRST NAME,LNAME LAST NAME AND DOB AS DATE OF BIRTH ?
SELECT FNAME AS "FIRST NAME", LNAME AS "LAST NAME", DOB AS "DATE OF BIRTH"
FROM EMPS;

14) WQTD ANNUAL SALARY AND JOB AS DESIGNATION FROM EMPS TABLE ?
SELECT SAL*12 AS "ANNUAL SALARY", JOB AS "DESIGNATION"
FROM EMPS;